### PR TITLE
Rethrow ConnectExceptions as runtime exceptions

### LINKED ISSUE #185: doGET does not distinguish between "not found" and timeout.
If the RecurlyClient suffers timeout, it logs "Execution error" and returns null. To the caller, it's indistinguishable from "not found". For example, when I tried to find an Account...  

```
	Account account = getRecurlyClient().getAccount(accountCode);
```

...and it timed out, a null account was returned rather than an exception. The following was logged (using version 0.8.0)...  

```
ERROR [Timer-7] (RecurlyClient.java:1483) - Execution error
java.util.concurrent.ExecutionException: java.net.ConnectException: connection timed out: goxpro-dev.recurly.com/104.16.113.53:443
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:232)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:151)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:159)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:142)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out: goxpro-dev.recurly.com/104.16.113.53:443
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:147)
	... 13 more
Caused by: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: goxpro-dev.recurly.com/104.16.113.53:443
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:139)
	... 8 more
```

...because RecurlyClient logged the exception but returned null...

```
    private <T> T callRecurlySafeXmlContent(final AsyncHttpClient.BoundRequestBuilder builder, @Nullable final Class<T> clazz) {
        try {
            return callRecurlyXmlContent(builder, clazz);
        } catch (IOException e) {
            log.warn("Error while calling Recurly", e);
            return null;
        } catch (ExecutionException e) {
            // Extract the errors exception, if any
            if (e.getCause() != null &&
                e.getCause().getCause() != null &&
                e.getCause().getCause() instanceof TransactionErrorException) {
                throw (TransactionErrorException) e.getCause().getCause();
            } else if (e.getCause() != null &&
                       e.getCause() instanceof TransactionErrorException) {
                // See https://github.com/killbilling/recurly-java-library/issues/16
                throw (TransactionErrorException) e.getCause();
            }
            log.error("Execution error", e);    // <<<<<<<< Here
            return null;    // <<<<<<<< And here
        } catch (InterruptedException e) {
            log.error("Interrupted while calling Recurly", e);
            return null;
        }
    }
```

### PR DESCRIPTION
**Pull request by aaron-suarez**
Fixes #185 

To test, configure the RecurlyClient to attempt to connect to an unsupported port (such as 81) and you will reliably get a "Connection Refused" error, which is an instance of `java.net.ConnectException`. A timeout error is also a `java.net.ConnectException`, though I haven't found a reliable way to test that particular one. If anyone has suggestions on a setup where a timeout can be reliable generated, please feel free to comment.

### CODE REVIEW

File: src/main/java/com/ning/billing/recurly/RecurlyClient.java [hunk 1]
```diff
@@ -2037,6 +2038,10 @@ private FluentCaseInsensitiveStringsMap callRecurlyNoContent(final AsyncHttpClie
         } catch (ExecutionException e) {
             // Extract the errors exception, if any
             if (e.getCause() != null &&
+                e.getCause() instanceof ConnectException) {
```
Comment (pierre) [inline src/main/java/com/ning/billing/recurly/RecurlyClient.java]: Nit: you shouldn't need the `null` check when using `instanceof`.

Comment (aaron-suarez) [reply src/main/java/com/ning/billing/recurly/RecurlyClient.java]: True. Took out the null check
